In [1]:
#Recommender Sytsem using k-means clstering

In [14]:
import pandas as pd

In [15]:
df1=pd.read_csv("/Users/sanatwalia/Desktop/playlist_videos.csv")

In [20]:
df1.head()

,title,views,likes,genre
0,Daft Punk - Infinity Repeating (2013 Demo) (fe...,7958035,186600,10
1,Daft Punk - Get Lucky (Official Audio) ft. Pha...,762886566,4935925,10
2,Daft Punk - Around The World (Official Music V...,57991478,654409,10
3,Daft Punk - One More Time (Official Video),485018882,2999412,10
4,Daft Punk - Within (Drumless Edition) (Officia...,310234,9937,10

In [22]:
df2=pd.read_csv('/Users/sanatwalia/Desktop/osdc/playlist_videos_new6.csv')

In [23]:
df2.head()

,title,duration,views,likes,genre,upload_date,url,playlist_url
0,Adha Pind,PT4M20S,19355904,124404,10,2018-11-27T10:21:41Z,https://www.youtube.com/watch?v=4BbrCKAKsgo,https://music.youtube.com/watch?v=H4nyLuecbi0&...
1,Santan Di Tasveer,PT6M16S,33489270,380771,10,2018-05-27T17:49:51Z,https://www.youtube.com/watch?v=-KqxoCdbzrc,https://music.youtube.com/watch?v=H4nyLuecbi0&...
2,Sajna,PT5M44S,16807053,111936,10,2016-06-22T01:19:34Z,https://www.youtube.com/watch?v=H4nyLuecbi0,https://music.youtube.com/watch?v=H4nyLuecbi0&...
3,Ik Vaari Saai Da Ban Ta Sahi,PT8M22S,30382987,175987,10,2014-11-07T07:06:16Z,https://www.youtube.com/watch?v=JO-dVwRPwpM,https://music.youtube.com/watch?v=H4nyLuecbi0&...
4,Sohne Mukhre Da,PT5M46S,12912174,71792,10,2018-08-31T05:23:43Z,https://www.youtube.com/watch?v=3TeQNDHSUzg,https://music.youtube.com/watch?v=H4nyLuecbi0&...

In [24]:

df3=pd.read_csv('/Users/sanatwalia/Desktop/osdc/playlist_videos_new5.csv')

In [25]:
df3.head()

,title,duration,views,likes,genre,upload_date,url,playlist_url
0,Down,PT3M13S,1533950,5902,10,2022-01-27T10:05:47Z,https://www.youtube.com/watch?v=LyGXvhsAJA0,https://music.youtube.com/browse/VLPL465FyR4NK...
1,Good For You – THBD (No Copyright Music),PT4M32S,18067696,118004,10,2016-05-24T17:00:01Z,https://www.youtube.com/watch?v=-K_YSjqKgvQ,https://music.youtube.com/browse/VLPL465FyR4NK...
2,Peyruis - My mind (ft. Sandrah),PT2M49S,359765,1076,22,2017-10-28T17:16:49Z,https://www.youtube.com/watch?v=XFDNV-Fimp8,https://music.youtube.com/browse/VLPL465FyR4NK...
3,drunk text me,PT3M34S,4342322,19565,10,2022-05-25T10:04:26Z,https://www.youtube.com/watch?v=pVl8azPJkeA,https://music.youtube.com/browse/VLPL465FyR4NK...
4,Easy On Me,PT3M45S,248460507,2030448,10,2021-10-14T23:01:00Z,https://www.youtube.com/watch?v=H9NJenpBV2I,https://music.youtube.com/browse/VLPL465FyR4NK...

In [26]:
df2.drop('upload_date',axis=1,inplace=True)
df2.drop('url',axis=1,inplace=True)
df2.drop('playlist_url',axis=1,inplace=True)

In [27]:
df2

                          title duration     views   likes  genre
0                     Adha Pind  PT4M20S  19355904  124404     10
1             Santan Di Tasveer  PT6M16S  33489270  380771     10
2                         Sajna  PT5M44S  16807053  111936     10
3  Ik Vaari Saai Da Ban Ta Sahi  PT8M22S  30382987  175987     10
4               Sohne Mukhre Da  PT5M46S  12912174   71792     10
5                    Pehla Wale  PT2M31S  13941721   88384     10
6                         Manke  PT4M42S  29507844  291313     10
7           Gadaar (Qaumi Dard)  PT5M15S  18307130  215263     10

In [28]:
df3.drop('upload_date',axis=1,inplace=True)
df3.drop('url',axis=1,inplace=True)
df3.drop('playlist_url',axis=1,inplace=True)

In [29]:
df3

,title,duration,views,likes,genre
0,Down,PT3M13S,1533950,5902,10
1,Good For You – THBD (No Copyright Music),PT4M32S,18067696,118004,10
2,Peyruis - My mind (ft. Sandrah),PT2M49S,359765,1076,22
3,drunk text me,PT3M34S,4342322,19565,10
4,Easy On Me,PT3M45S,248460507,2030448,10
5,Myspace – kimengumi (No Copyright Music),PT2M19S,2058891,12622,10
6,Honest (feat. C. Tangana),PT3M36S,1825985,1565,10
7,Skyfall,PT4M47S,70398678,736931,10
8,We Are One,PT3M49S,440384,4758,10
9,Vibe With Me,PT2M54S,251522,3212,10
10,Perfect,PT4M24S,334815493,2971316,10
11,Summertime Sadness,PT4M25S,156398918,1584681,10
12,I'm Not The Only One,PT4M,268826054,1584475,10
13,Be Alright,PT3M17S,74391186,636468,10
14,Move Your Body,PT2M38S,14935617,157690,10
15,Lights,PT3M28S,77330,452,10
16,Only Love Can Hurt Like This,PT3M53S,140189697,1528193,10
17,Rolling in the Deep,PT3M49S,50270979,402875,10
18,Bloody Mary,PT4M5S,68566940,633671,10
19,Nostalgia,PT3M23S,305948,2807,10
20,greedy,PT2M12S,26012356,322056,10
21,Revolt,PT3M48S,38729,307,10
22,Blinding Lights,PT3M22S,629757538,4719547,10
23,Thinking out Loud,PT4M42S,200879424,1572295,10
24,Viva La Vida,PT4M2S,119106665,929923,10
25,Paparazzi,PT3M29S,37902482,346978,10
26,Wild Flower,PT3M26S,340011,2035,10
27,"Neethanae (From ""Mersal"")",PT4M29S,5571563,24850,10
28,Take It Easy,PT2M21S,58631,549,10
29,Just Give Me a Reason,PT4M3S,10943152,79393,10
30,Say It Right,PT3M44S,89245469,816487,10
31,"No, It's Not a Nightmare",PT3M34S,2158394,768,10
32,Always Remember Us This Way,PT3M31S,233947633,1337092,10
33,All of Me,PT4M31S,1702548,10411,10
34,comethru,PT3M2S,70506084,416240,10
35,vampire,PT3M40S,21123966,240200,10
36,Great Days,PT3M43S,381268,4079,10
37,Apocalypse,PT4M51S,60473131,694345,10
38,Someone Like You,PT4M46S,101796909,637583,10
39,See You Again (feat. Charlie Puth),PT3M50S,20533338,179960,10
40,Hip Hop Rap Instrumental (Crying Over You) – c...,PT2M21S,5074766,82094,10
41,Love You Like A Love Song,PT3M9S,163320488,1338181,10
42,Cheap Thrills,PT3M31S,41285780,386148,10
43,Unstoppable,PT3M38S,25383176,219361,10
44,A Sky Full of Stars,PT4M28S,153045130,1208348,10
45,Enna Solla Pogirai,PT6M1S,9894266,56123,10
46,Paint The Town Red,PT3M51S,34612049,443727,10
47,Shape of You,PT3M54S,437042125,3400920,10
48,Dandelions,PT3M54S,180873428,1913966,10
49,Annul Maelae,PT5M23S,4496433,26892,10

In [30]:
df2.drop('duration',axis=1,inplace=True)
df3.drop('duration',axis=1,inplace=True)

In [31]:
df2

                          title     views   likes  genre
0                     Adha Pind  19355904  124404     10
1             Santan Di Tasveer  33489270  380771     10
2                         Sajna  16807053  111936     10
3  Ik Vaari Saai Da Ban Ta Sahi  30382987  175987     10
4               Sohne Mukhre Da  12912174   71792     10
5                    Pehla Wale  13941721   88384     10
6                         Manke  29507844  291313     10
7           Gadaar (Qaumi Dard)  18307130  215263     10

In [33]:
result = pd.concat([df1, df2, df3], ignore_index=True)

In [34]:
result

,title,views,likes,genre
0,Daft Punk - Infinity Repeating (2013 Demo) (fe...,7958035,186600,10
1,Daft Punk - Get Lucky (Official Audio) ft. Pha...,762886566,4935925,10
2,Daft Punk - Around The World (Official Music V...,57991478,654409,10
3,Daft Punk - One More Time (Official Video),485018882,2999412,10
4,Daft Punk - Within (Drumless Edition) (Officia...,310234,9937,10
...,...,...,...,...
85,Enna Solla Pogirai,9894266,56123,10
86,Paint The Town Red,34612049,443727,10
87,Shape of You,437042125,3400920,10
88,Dandelions,180873428,1913966,10
89,Annul Maelae,4496433,26892,10

In [35]:
title=result['title'].unique()

In [36]:
title_key=[i for i in range(1,len(title)+1)]

In [39]:
play_dict=dict(zip(title_key,title))

In [40]:
play_dict

{1: 'Daft Punk - Infinity Repeating (2013 Demo) (feat. Julian Casablancas+The Voidz)',
 2: 'Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers',
 3: 'Daft Punk - Around The World (Official Music Video Remastered)',
 4: 'Daft Punk - One More Time (Official Video)',
 5: 'Daft Punk - Within (Drumless Edition) (Official Lyric Video)',
 6: 'Daft Punk - Harder, Better, Faster, Stronger (Official Video)',
 7: 'Daft Punk - Veridis Quo (Official Video)',
 8: 'Daft Punk - Technologic (Official Video)',
 9: 'Daft Punk - Aerodynamic (Official Video)',
 10: 'Daft Punk - Lose Yourself to Dance (Official Version)',
 11: 'Daft Punk - Da Funk (Official Audio)',
 12: 'Daft Punk - Digital Love (Official Audio)',
 13: 'Daft Punk - Instant Crush (Video) ft. Julian Casablancas',
 14: 'The Weeknd - Starboy ft. Daft Punk (Official Video)',
 15: 'Daft Punk - High Life (Official Video)',
 16: 'Daft Punk - Derezzed (from TRON: Legacy)',
 17: 'Daft Punk - Teachers (Official Audio)',
 18: 'Daft Punk - Face to Face (Official Video)',
 19: 'The Weeknd - I Feel It Coming ft. Daft Punk (Official Video)',
 20: 'Daft Punk - Something About Us (Official Video)',
 21: 'Daft Punk - Robot Rock (Official Video)',
 22: "Daft Punk - Doin' it Right (Official Audio) ft. Panda Bear",
 23: 'Daft Punk - Giorgio by Moroder (Official Audio)',
 24: 'Daft Punk - Voyager (Official Video)',
 25: 'Daft Punk - Television Rules the Nation (Official Audio)',
 26: 'End of Line',
 27: 'Daft Punk - Epilogue',
 28: 'Daft Punk - GLBTM (Studio Outtakes) (Official Audio)',
 29: 'Daft Punk - The Writing of Fragments of Time (RAM 10th Anniversary) ft. Todd Edwards',
 30: 'Daft Punk - Horizon (Japan CD) (Official Audio)',
 31: 'Daft Punk - Prime (2012 Unfinished) (Official Audio)',
 32: 'Daft Punk - Horizon Ouverture (Official Audio)',
 33: 'Adha Pind',
 34: 'Santan Di Tasveer',
 35: 'Sajna',
 36: 'Ik Vaari Saai Da Ban Ta Sahi',
 37: 'Sohne Mukhre Da',
 38: 'Pehla Wale',
 39: 'Manke',
 40: 'Gadaar (Qaumi Dard)',
 41: 'Down',
 42: 'Good For You – THBD (No Copyright Music)',
 43: 'Peyruis - My mind (ft. Sandrah)',
 44: 'drunk text me',
 45: 'Easy On Me',
 46: 'Myspace – kimengumi (No Copyright Music)',
 47: 'Honest (feat. C. Tangana)',
 48: 'Skyfall',
 49: 'We Are One',
 50: 'Vibe With Me',
 51: 'Perfect',
 52: 'Summertime Sadness',
 53: "I'm Not The Only One",
 54: 'Be Alright',
 55: 'Move Your Body',
 56: 'Lights',
 57: 'Only Love Can Hurt Like This',
 58: 'Rolling in the Deep',
 59: 'Bloody Mary',
 60: 'Nostalgia',
 61: 'greedy',
 62: 'Revolt',
 63: 'Blinding Lights',
 64: 'Thinking out Loud',
 65: 'Viva La Vida',
 66: 'Paparazzi',
 67: 'Wild Flower',
 68: 'Neethanae (From "Mersal")',
 69: 'Take It Easy',
 70: 'Just Give Me a Reason',
 71: 'Say It Right',
 72: "No, It's Not a Nightmare",
 73: 'Always Remember Us This Way',
 74: 'All of Me',
 75: 'comethru',
 76: 'vampire',
 77: 'Great Days',
 78: 'Apocalypse',
 79: 'Someone Like You',
 80: 'See You Again (feat. Charlie Puth)',
 81: 'Hip Hop Rap Instrumental (Crying Over You) – christophermorrow (No Copyright Music)',
 82: 'Love You Like A Love Song',
 83: 'Cheap Thrills',
 84: 'Unstoppable',
 85: 'A Sky Full of Stars',
 86: 'Enna Solla Pogirai',
 87: 'Paint The Town Red',
 88: 'Shape of You',
 89: 'Dandelions',
 90: 'Annul Maelae'}

In [41]:
title_dict=dict(zip(title,title_key))

In [42]:
title_dict

{'Daft Punk - Infinity Repeating (2013 Demo) (feat. Julian Casablancas+The Voidz)': 1,
 'Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers': 2,
 'Daft Punk - Around The World (Official Music Video Remastered)': 3,
 'Daft Punk - One More Time (Official Video)': 4,
 'Daft Punk - Within (Drumless Edition) (Official Lyric Video)': 5,
 'Daft Punk - Harder, Better, Faster, Stronger (Official Video)': 6,
 'Daft Punk - Veridis Quo (Official Video)': 7,
 'Daft Punk - Technologic (Official Video)': 8,
 'Daft Punk - Aerodynamic (Official Video)': 9,
 'Daft Punk - Lose Yourself to Dance (Official Version)': 10,
 'Daft Punk - Da Funk (Official Audio)': 11,
 'Daft Punk - Digital Love (Official Audio)': 12,
 'Daft Punk - Instant Crush (Video) ft. Julian Casablancas': 13,
 'The Weeknd - Starboy ft. Daft Punk (Official Video)': 14,
 'Daft Punk - High Life (Official Video)': 15,
 'Daft Punk - Derezzed (from TRON: Legacy)': 16,
 'Daft Punk - Teachers (Official Audio)': 17,
 'Daft Punk - Face to Face (Official Video)': 18,
 'The Weeknd - I Feel It Coming ft. Daft Punk (Official Video)': 19,
 'Daft Punk - Something About Us (Official Video)': 20,
 'Daft Punk - Robot Rock (Official Video)': 21,
 "Daft Punk - Doin' it Right (Official Audio) ft. Panda Bear": 22,
 'Daft Punk - Giorgio by Moroder (Official Audio)': 23,
 'Daft Punk - Voyager (Official Video)': 24,
 'Daft Punk - Television Rules the Nation (Official Audio)': 25,
 'End of Line': 26,
 'Daft Punk - Epilogue': 27,
 'Daft Punk - GLBTM (Studio Outtakes) (Official Audio)': 28,
 'Daft Punk - The Writing of Fragments of Time (RAM 10th Anniversary) ft. Todd Edwards': 29,
 'Daft Punk - Horizon (Japan CD) (Official Audio)': 30,
 'Daft Punk - Prime (2012 Unfinished) (Official Audio)': 31,
 'Daft Punk - Horizon Ouverture (Official Audio)': 32,
 'Adha Pind': 33,
 'Santan Di Tasveer': 34,
 'Sajna': 35,
 'Ik Vaari Saai Da Ban Ta Sahi': 36,
 'Sohne Mukhre Da': 37,
 'Pehla Wale': 38,
 'Manke': 39,
 'Gadaar (Qaumi Dard)': 40,
 'Down': 41,
 'Good For You – THBD (No Copyright Music)': 42,
 'Peyruis - My mind (ft. Sandrah)': 43,
 'drunk text me': 44,
 'Easy On Me': 45,
 'Myspace – kimengumi (No Copyright Music)': 46,
 'Honest (feat. C. Tangana)': 47,
 'Skyfall': 48,
 'We Are One': 49,
 'Vibe With Me': 50,
 'Perfect': 51,
 'Summertime Sadness': 52,
 "I'm Not The Only One": 53,
 'Be Alright': 54,
 'Move Your Body': 55,
 'Lights': 56,
 'Only Love Can Hurt Like This': 57,
 'Rolling in the Deep': 58,
 'Bloody Mary': 59,
 'Nostalgia': 60,
 'greedy': 61,
 'Revolt': 62,
 'Blinding Lights': 63,
 'Thinking out Loud': 64,
 'Viva La Vida': 65,
 'Paparazzi': 66,
 'Wild Flower': 67,
 'Neethanae (From "Mersal")': 68,
 'Take It Easy': 69,
 'Just Give Me a Reason': 70,
 'Say It Right': 71,
 "No, It's Not a Nightmare": 72,
 'Always Remember Us This Way': 73,
 'All of Me': 74,
 'comethru': 75,
 'vampire': 76,
 'Great Days': 77,
 'Apocalypse': 78,
 'Someone Like You': 79,
 'See You Again (feat. Charlie Puth)': 80,
 'Hip Hop Rap Instrumental (Crying Over You) – christophermorrow (No Copyright Music)': 81,
 'Love You Like A Love Song': 82,
 'Cheap Thrills': 83,
 'Unstoppable': 84,
 'A Sky Full of Stars': 85,
 'Enna Solla Pogirai': 86,
 'Paint The Town Red': 87,
 'Shape of You': 88,
 'Dandelions': 89,
 'Annul Maelae': 90}

In [52]:
def replace(column_name):
    new_dict={'Daft Punk - Infinity Repeating (2013 Demo) (feat. Julian Casablancas+The Voidz)': 1,
 'Daft Punk - Get Lucky (Official Audio) ft. Pharrell Williams, Nile Rodgers': 2,
 'Daft Punk - Around The World (Official Music Video Remastered)': 3,
 'Daft Punk - One More Time (Official Video)': 4,
 'Daft Punk - Within (Drumless Edition) (Official Lyric Video)': 5,
 'Daft Punk - Harder, Better, Faster, Stronger (Official Video)': 6,
 'Daft Punk - Veridis Quo (Official Video)': 7,
 'Daft Punk - Technologic (Official Video)': 8,
 'Daft Punk - Aerodynamic (Official Video)': 9,
 'Daft Punk - Lose Yourself to Dance (Official Version)': 10,
 'Daft Punk - Da Funk (Official Audio)': 11,
 'Daft Punk - Digital Love (Official Audio)': 12,
 'Daft Punk - Instant Crush (Video) ft. Julian Casablancas': 13,
 'The Weeknd - Starboy ft. Daft Punk (Official Video)': 14,
 'Daft Punk - High Life (Official Video)': 15,
 'Daft Punk - Derezzed (from TRON: Legacy)': 16,
 'Daft Punk - Teachers (Official Audio)': 17,
 'Daft Punk - Face to Face (Official Video)': 18,
 'The Weeknd - I Feel It Coming ft. Daft Punk (Official Video)': 19,
 'Daft Punk - Something About Us (Official Video)': 20,
 'Daft Punk - Robot Rock (Official Video)': 21,
 "Daft Punk - Doin' it Right (Official Audio) ft. Panda Bear": 22,
 'Daft Punk - Giorgio by Moroder (Official Audio)': 23,
 'Daft Punk - Voyager (Official Video)': 24,
 'Daft Punk - Television Rules the Nation (Official Audio)': 25,
 'End of Line': 26,
 'Daft Punk - Epilogue': 27,
 'Daft Punk - GLBTM (Studio Outtakes) (Official Audio)': 28,
 'Daft Punk - The Writing of Fragments of Time (RAM 10th Anniversary) ft. Todd Edwards': 29,
 'Daft Punk - Horizon (Japan CD) (Official Audio)': 30,
 'Daft Punk - Prime (2012 Unfinished) (Official Audio)': 31,
 'Daft Punk - Horizon Ouverture (Official Audio)': 32,
 'Adha Pind': 33,
 'Santan Di Tasveer': 34,
 'Sajna': 35,
 'Ik Vaari Saai Da Ban Ta Sahi': 36,
 'Sohne Mukhre Da': 37,
 'Pehla Wale': 38,
 'Manke': 39,
 'Gadaar (Qaumi Dard)': 40,
 'Down': 41,
 'Good For You – THBD (No Copyright Music)': 42,
 'Peyruis - My mind (ft. Sandrah)': 43,
 'drunk text me': 44,
 'Easy On Me': 45,
 'Myspace – kimengumi (No Copyright Music)': 46,
 'Honest (feat. C. Tangana)': 47,
 'Skyfall': 48,
 'We Are One': 49,
 'Vibe With Me': 50,
 'Perfect': 51,
 'Summertime Sadness': 52,
 "I'm Not The Only One": 53,
 'Be Alright': 54,
 'Move Your Body': 55,
 'Lights': 56,
 'Only Love Can Hurt Like This': 57,
 'Rolling in the Deep': 58,
 'Bloody Mary': 59,
 'Nostalgia': 60,
 'greedy': 61,
 'Revolt': 62,
 'Blinding Lights': 63,
 'Thinking out Loud': 64,
 'Viva La Vida': 65,
 'Paparazzi': 66,
 'Wild Flower': 67,
 'Neethanae (From "Mersal")': 68,
 'Take It Easy': 69,
 'Just Give Me a Reason': 70,
 'Say It Right': 71,
 "No, It's Not a Nightmare": 72,
 'Always Remember Us This Way': 73,
 'All of Me': 74,
 'comethru': 75,
 'vampire': 76,
 'Great Days': 77,
 'Apocalypse': 78,
 'Someone Like You': 79,
 'See You Again (feat. Charlie Puth)': 80,
 'Hip Hop Rap Instrumental (Crying Over You) – christophermorrow (No Copyright Music)': 81,
 'Love You Like A Love Song': 82,
 'Cheap Thrills': 83,
 'Unstoppable': 84,
 'A Sky Full of Stars': 85,
 'Enna Solla Pogirai': 86,
 'Paint The Town Red': 87,
 'Shape of You': 88,
 'Dandelions': 89,
 'Annul Maelae': 90}
    return new_dict[column_name]

In [54]:
result['title']=result['title'].apply(replace)

In [55]:
result

    title      views    likes  genre
0       1    7958035   186600     10
1       2  762886566  4935925     10
2       3   57991478   654409     10
3       4  485018882  2999412     10
4       5     310234     9937     10
..    ...        ...      ...    ...
85     86    9894266    56123     10
86     87   34612049   443727     10
87     88  437042125  3400920     10
88     89  180873428  1913966     10
89     90    4496433    26892     10

[90 rows x 4 columns]

In [58]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler




# Extract the relevant column for clustering
X = result[['views','likes','genre']]

# Standardize the features using StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Specify the number of clusters
n_clusters = 11

# Perform K-means clustering
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
result['cluster'] = kmeans.fit_predict(X_scaled)

# Create a dictionary with cluster number as key and list of cluster members as value
cluster_dict = {}
for cluster_num in range(n_clusters):
    members = result[result['cluster'] == cluster_num]['title'].tolist()
    cluster_dict[cluster_num] = members

# Print the DataFrame with cluster information
print("\nDataFrame with Cluster Information:")
print(result)

# Print the Cluster Dictionary
print("\nCluster Dictionary:")
print(cluster_dict)

DataFrame with Cluster Information:
    title      views    likes  genre  cluster
0       1    7958035   186600     10        9
1       2  762886566  4935925     10        1
2       3   57991478   654409     10        8
3       4  485018882  2999412     10        7
4       5     310234     9937     10        9
..    ...        ...      ...    ...      ...
85     86    9894266    56123     10        9
86     87   34612049   443727     10        0
87     88  437042125  3400920     10        7
88     89  180873428  1913966     10        4
89     90    4496433    26892     10        9

[90 rows x 5 columns]

Cluster Dictionary:
{0: [7, 8, 9, 16, 18, 22, 34, 36, 39, 40, 58, 61, 66, 75, 76, 80, 83, 84, 87], 1: [2, 63], 2: [43], 3: [14], 4: [10, 45, 53, 64, 73, 89], 5: [13], 6: [19], 7: [4, 51, 88], 8: [3, 20, 21, 23, 48, 54, 59, 65, 71, 78, 79], 9: [1, 5, 11, 12, 15, 17, 24, 25, 26, 28, 29, 30, 31, 32, 33, 35, 37, 38, 41, 42, 44, 46, 47, 49, 50, 55, 56, 60, 62, 67, 68, 69, 70, 72, 74, 77, 81, 86, 90], 10: [6, 27, 52, 57, 82, 85]}

/Users/sanatwalia/anaconda3/envs/notebook/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

In [60]:
cluster_dict

{0: [7, 8, 9, 16, 18, 22, 34, 36, 39, 40, 58, 61, 66, 75, 76, 80, 83, 84, 87],
 1: [2, 63],
 2: [43],
 3: [14],
 4: [10, 45, 53, 64, 73, 89],
 5: [13],
 6: [19],
 7: [4, 51, 88],
 8: [3, 20, 21, 23, 48, 54, 59, 65, 71, 78, 79],
 9: [1,
  5,
  11,
  12,
  15,
  17,
  24,
  25,
  26,
  28,
  29,
  30,
  31,
  32,
  33,
  35,
  37,
  38,
  41,
  42,
  44,
  46,
  47,
  49,
  50,
  55,
  56,
  60,
  62,
  67,
  68,
  69,
  70,
  72,
  74,
  77,
  81,
  86,
  90],
 10: [6, 27, 52, 57, 82, 85]}

In [61]:
# Assuming you have a dictionary with song title IDs as keys and song titles as values
# song_title_dict = {
#     101: 'Song1',
#     102: 'Song2',
#     103: 'Song3',
#     104: 'Song4',
#     105: 'Song5',
#     106: 'Song6',
#     107: 'Song7',
#     108: 'Song8',
#     109: 'Song9',
# }

# Another dictionary with cluster IDs and lists of title IDs
# cluster_titles_dict = {
#     1: [101, 103, 107],
#     2: [102, 105, 108],
#     3: [104, 106, 109],
# }

# Function to recommend songs based on the number of songs from the same cluster in a playlist
def recommend_songs_in_playlist(playlist, song_title_dict, cluster_titles_dict, threshold=3):
    cluster_counts = {}

    # Count the number of songs from each cluster in the playlist
    for title_id in playlist:
        for cluster_id, title_ids in cluster_titles_dict.items():
            if title_id in title_ids:
                cluster_counts[cluster_id] = cluster_counts.get(cluster_id, 0) + 1

    # Recommend songs from clusters with more than the threshold number of songs
    recommended_titles = []
    for cluster_id, count in cluster_counts.items():
        if count > threshold and cluster_id in cluster_titles_dict:
            recommended_titles.extend(cluster_titles_dict[cluster_id])

    # Convert title IDs back to song titles
    recommended_songs = [song_title_dict[title_id] for title_id in recommended_titles]

    return recommended_songs

# Example playlist with title IDs
playlist = [1,7,8,9,1,4,6,8,3,2]

# Get recommended songs for the playlist
recommendations = recommend_songs_in_playlist(playlist,play_dict ,cluster_dict )

# Print the recommendations
print(f'Recommended Songs: {recommendations}')

Recommended Songs: ['Daft Punk - Veridis Quo (Official Video)', 'Daft Punk - Technologic (Official Video)', 'Daft Punk - Aerodynamic (Official Video)', 'Daft Punk - Derezzed (from TRON: Legacy)', 'Daft Punk - Face to Face (Official Video)', "Daft Punk - Doin' it Right (Official Audio) ft. Panda Bear", 'Santan Di Tasveer', 'Ik Vaari Saai Da Ban Ta Sahi', 'Manke', 'Gadaar (Qaumi Dard)', 'Rolling in the Deep', 'greedy', 'Paparazzi', 'comethru', 'vampire', 'See You Again (feat. Charlie Puth)', 'Cheap Thrills', 'Unstoppable', 'Paint The Town Red']